on: [push]

jobs:
  build_package_job:
    runs-on: ubuntu-latest
    name: A job to build the package
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: checkout
      - name: Build package action step
        id: buildstep
        uses: IdyllicHappiness/aurPackageBuilderUsingParu@v9
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}/output/*
